// Generated by CoffeeScript 1.7.1
(function() {
  var ObjectId, User, addUser, async, bcrypt, cleanup, connCb, db, mongoose, users, util, uuid, _;

  util = require("util");

  mongoose = require("mongoose");

  async = require("async");

  ObjectId = mongoose.Types.ObjectId;

  uuid = require("node-uuid");

  bcrypt = require('bcrypt');

  _ = require('underscore');

  console.log("Bootstrap: Connecting to DB");

  connCb = function(err) {
    if (err) {
      return console.log("Post Install Bootstrap: Error connecting to Mongo - " + err);
    }
    return console.log("Bootstrap: Connected API to Mongo");
  };

  db = require("../lib/shared/models/mongo");

  User = require("../lib/shared/models/user").User;

  users = [
    {
      firstName: "first",
      lastName: "last",
      email: "email@email.com",
      password: "password",
      accessToken: uuid.v1()
    }
  ];

  addUser = function(user, callback) {
    return bcrypt.genSalt(10, function(err, salt) {
      return bcrypt.hash(user.password, salt, function(err, hash) {
        if (err) {
          callback(err);
        }
        _.extend(user, {
          password: hash
        });
        return User.update({
          email: user.email
        }, {
          $set: user
        }, {
          upsert: true
        }, function(err) {
          return callback();
        });
      });
    });
  };

  cleanup = function() {
    console.log("Bootstrap: disconnecting from mongo yoooo");
    return mongoose.disconnect();
  };

  async.forEach(users, addUser, function(err) {
    return cleanup();
  });

}).call(this);
